---
title: "My english activity log"
author:
  - name: Rémy Harazin
date: 09-25-2019
output:
  distill::distill_article:
    self_contained: false
---

I started to improve my English by myself more than 3 years ago.
It started when I changed the language of a game I played (League of Legends) to English.
Then I played all of my games in English, and I set my phone in English as well.
In the beginning of the academic year, I set my computer language to English too.

When I watch something like tv shows, animes, videos, I try to watch them in English with English subtitles if it's possible.
For example, these days, I'm watching Rick and Morty on Netflix, in English with English subtitles.
I'm also watching seasonal animes in japanese, but with english subtiles.

TV Show/Video

05/11/19 Second season of the netflix serie "The end of the F***ing world", it's in english (UK) with english subtitles

24/12/19 Homeland on netflix, it's a tv show about counter-terrorism in USA

03/01/19 Ted Talks about self-improvement

20/02/20 Homeland

27/02/20 Homeland

01/03/20 Youtube video about tumor in big animals

Video Games 

29/02/20 Bioshock 2 


